### ISSUE TITLE
Freshly started server accepting connections, but not starting replication

### ISSUE THREAD

**Issue by waynerobinson** [rusuly/mysql_cdc#6]
There appears to be a case where a freshly started MySQL server is accepting a connection from mysql_cdc, but ignoring the request to start sending replication events.

Instead, a call to `replicate()` just blocks, even if blocking is disabled, because it never receives any data.

If the server is just swallowing the request to start, is it possible to instead wait for the `FORMAT_DESCRIPTION_EVENT` event and, on a timeout, raise an error or potentially attempt to connect again?

At the moment our workaround is to attempt to connect to the server using `connect()` and, when connected, to wait 10 seconds before attempting to start calling `replicate()` however, this is both slow in the normal case and potentially still prone to errors if 10 seconds isn't enough for the server to actually be ready to accept new replicas.

**Comment by waynerobinson** [comment]
Would it make sense to set the read timeout on the connection to something like 2x the heartbeat? Something like:

```rust
impl PacketChannel {
    pub fn new(options: &ReplicaOptions) -> Result<Self, io::Error> {
        let address: String = format!("{}:{}", options.hostname, options.port.to_string());
        let stream = TcpStream::connect(address)?;
        stream.set_read_timeout(Some(options.heartbeat_interval.mul(2)))?;
        Ok(Self { stream })
    }
}
```

This would effectively implement heartbeat detection too, as long as whatever is calling `replicate()` has implemented automatic reconnection.

**Comment by rusuly** [comment]
Hi,
I think the heartbeat check on the channel would be the best option here. The feature was in the [todo list](https://github.com/rusuly/mysql_cdc/issues/1) but I just added the read timeout handling and published the new version to crates. You will need to check if it works as expected in your environment.
Unfortunately maintaining the repository is limited because of russian invasion of Ukraine

**Comment by waynerobinson** [comment]
Looks good! Thanks for the confirmation.
